sudo: false
language: python
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.6
            - python3.6-dev
            - python3.7
            - python3.7-dev
            - python3.8
            - python3.8-dev
            - python3.8-venv
            - python3.9
            - python3.9-dev
            - python3.9-venv
env:
    - TOXENV=py36-2.2
    - TOXENV=py36-3.0
    - TOXENV=py36-3.1
    - TOXENV=py36-djdev
    - TOXENV=py37-2.2
    - TOXENV=py37-3.0
    - TOXENV=py37-3.1
    - TOXENV=py37-djdev
    - TOXENV=py38-2.2
    - TOXENV=py38-3.0
    - TOXENV=py38-3.1
    - TOXENV=py38-djdev
    - TOXENV=py39-2.2
    - TOXENV=py39-3.0
    - TOXENV=py39-3.1
    - TOXENV=py39-djdev
matrix:
    allow_failures:
        - env: TOXENV=py36-djdev
        - env: TOXENV=py37-djdev
        - env: TOXENV=py38-djdev
        - env: TOXENV=py39-djdev
install:
    - pip install virtualenv
    - pip install tox
script:
    - export PYTHONPATH=$PYTHONPATH:`pwd`
    - tox
