sudo: false
language: python
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.5
            - python3.5-dev
            - python3.6
            - python3.6-dev
            - python3.7
            - python3.7-dev
            - python3.8
            - python3.8-dev
            - python3.8-venv
env:
    - TOXENV=py35-1.9
    - TOXENV=py35-1.10
    - TOXENV=py35-1.11
    - TOXENV=py35-2.0
    - TOXENV=py35-2.1
    - TOXENV=py35-2.2
    - TOXENV=py36-1.9
    - TOXENV=py36-1.10
    - TOXENV=py36-1.11
    - TOXENV=py36-2.0
    - TOXENV=py36-2.1
    - TOXENV=py36-2.2
    - TOXENV=py36-3.0
    - TOXENV=py37-1.9
    - TOXENV=py37-1.10
    - TOXENV=py37-1.11
    - TOXENV=py37-2.0
    - TOXENV=py37-2.1
    - TOXENV=py37-2.2
    - TOXENV=py37-3.0
    - TOXENV=py38-2.2
    - TOXENV=py38-3.0
matrix:
    allow_failures:
      - env: TOXENV=py36-3.0
      - env: TOXENV=py37-3.0
      - env: TOXENV=py38-3.0
install:
    - pip install tox
script:
    - export PYTHONPATH=$PYTHONPATH:`pwd`
    - tox
